### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by muneebahmad0600** [furkankurt/pinch_zoom_image_last#5]
Hello there, 
I am using your plugin, when i try to zoom in while debudding, flutter throws this error.
"MissingPluginException (MissingPluginException(No implementation found for method hideStatusBar on channel pinch_zoom_image))".
i guess the "hideStatusBar()" is missing or something.
Also.. I am using this in like an instagram clone, I have bottom navigation bar, so when trying to zoom sometimes the bottom nav tab starts to change.

**Comment by bynicodevelop** [comment]
I have the same problem :D

**Comment by callumclift** [comment]
also have the same problem

**Comment by darinkolev** [comment]
Same here. Any ideas?
